import React from "react";
import {
  MailOutlined,
  AppstoreOutlined,
  SettingOutlined,
  UnorderedListOutlined,
  AlibabaOutlined,
} from "@ant-design/icons";
import Image from "next/image";
import styles from "@/styles/Home.module.css";

import Head from "next/head";
import Link from "next/link";
import { Layout, Menu, Col, Row } from "antd";

const { Header } = Layout;

export default function NavbarComponents() {
  const navigationAdmin = [
    {
      label: <Link href="/admin/parks">Park</Link>,
      key: "manu-1",
      // icon: <MailOutlined />,
    },
    {
      label: <Link href="/admin/checkpoints">Checkpoints</Link>,
      key: "manu-2",
      // icon: <AppstoreOutlined />,
    },
    {
      label: <Link href="/admin/paths">Paths</Link>,
      key: "manu-3",
    },
    {
      label: <Link href="/admin/users">Users</Link>,
      key: "menu-4",
    },
    {
      lable: "sub menu",
      key: "summenu",
      icon: <UnorderedListOutlined />,
      children: [
        {
          label: <Link href="/admin/logs">Logs</Link>,
          key: "summenu-2",
        },
        {
          label: <Link href="/admin/laps">Laps</Link>,
          key: "summenu-3",
        },
        {
          label: <Link href="/admin/runs">Runs</Link>,
          key: "summenu-4",
        },
        {
          label: <Link href="/admin/path-checkpoints">PathCheckpoints</Link>,
          key: "summenu-5",
        },
        {
          label: <Link href="/admin/checkPath">CheckPath</Link>,
          key: "summenu-6",
        },
      ],
    },
  ];
  return (
    <>
      <Header className="header">
        <Row>
          <Head>
            <title>Run Tracking App</title>
            <meta name="description" content="Generated by create next app" />
            <meta
              name="viewport"
              content="width=device-width, initial-scale=1"
            />
            <link rel="icon" href="/favicon.ico" />
          </Head>

          {/* <Row justify="space-around" align="middle"> */}
          {/* <Col span={2} justify="space-evenly"> */}
          <div className="logo">
            <Link href="/index">
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                className={styles.vercelLogo}
                width={100}
                height={24}
                priority
              />
            </Link>
          </div>
          <Col span={1}></Col>
          <Menu
            className="relative ml-3 grid grid-cols-1"
            theme="dark"
            mode="horizontal"
            items={navigationAdmin}
          />
        </Row>
      </Header>
    </>
  );
}
